In [5]:
import pandas as pd
from IPython.display import display, HTML

# Показывать все колонки
pd.set_option('display.max_columns', None)

# Настроить стиль для горизонтальной прокрутки
def show_scrollable(df):
    display(HTML(df.to_html(notebook=True, max_rows=20, max_cols=None, escape=False)))
    
    # Альтернативно, если нужен скролл:
    display(HTML(f"""
        <div style="overflow-x: auto; max-width:100%;">
            {df.to_html()}
        </div>
    """))

In [186]:
valid_app_data = pd.read_parquet(r'C:\Users\makog\ai_hac\hackathon\data\valid_app_data.parquet')

In [187]:
valid_app_data.tail()

,APPLICATIONID,CREATE_DATE,CREATE_DATETIME,DATA_ISSUE,VINTAGE,PRODUCT_GROUP,PURPOSE_LOAN,OPV_REASON,KANAL_PRODAZH,TOTALAMOUNT,SUM_CREDIT_KZT,BRANCH,SPF,APPLICATION_ISA0AUTO,MNG_NAME_LOGIN_INIT,MNG_NAME_INIT,DM5DPD1GCVPSUM,DM5DPD1SALARYSUM,DM5EXPSUM,DM5INCSUM,DM5INC,DM5EXP,DM7INC,DM7EXP,DM6SCOREN6PD,DM6SCOREN6,FINALKDN,CREDITTERM_RBL0,CLI_AGE,GENDER,MARITALSTATUS,DEPENDANT_COUNT,COMPANY_NAME,REGREGION,REGCOUNTY,REGTOWN,BIRTHCOUNTRY,BKI,VKI
30261,Д\286\012275441,2024-12-26,26.12.2024 20:52,27.12.2024,2024_12,Доверительный,На потребительские цели,Онлайн СБОЛ,B-Bank,150 000,150 000,Кокшетау,"Кокшетау, Операционный отдел",Улица,servws,servws servws,"311 175,0",0.0,"1 484 270,7","1 481 724,7",0,0,0,1,"0,00768049","793,8556068",None,12,52,Женский,Холост/Не замужем,0,ТОО Real Export,Сандыктауский район,Акмолинская область,с.Балкашино,РЕСПУБЛИКА КАЗАХСТАН ...,Хорошая,Отсутствует
30272,Д\286\012141252,2024-12-12,12.12.2024 12:19,12.12.2024,2024_12,Доверительный,На потребительские цели,Онлайн СБОЛ,QR,1 500 000,1 000 000,Тараз,"Тараз, ОО Сектор по обслуживанию физических лиц",Улица,u18026,Молдир Сарманбетова,-,0.0,"553 521,7","553 468,8",0,1,0,0,"0,04988399","760,0928074","0,3715",60,43,Женский,Холост/Не замужем,1,,Жуалынский район,Жамбылская область,с.им.Б.Момышулы,РЕСПУБЛИКА КАЗАХСТАН ...,Хорошая,Отсутствует
30273,Д\286\012161697,2024-12-14,14.12.2024 11:52,14.12.2024,2024_12,Доверительный,На потребительские цели,Онлайн СБОЛ,B-Bank,150 000,150 000,Тараз,"Тараз, СПФ №1 ""Алатау""",Улица,servws,servws servws,-,0.0,"410 992,0","411 387,7",1,0,0,0,"0,02798233","777,6141384",None,24,47,Женский,Холост/Не замужем,1,,г.Тараз,Жамбылская область,Ойшиликский сельский округ,РЕСПУБЛИКА КАЗАХСТАН ...,Хорошая,Хорошая
30274,Д\286\012248249,2024-12-24,24.12.2024 10:04,24.12.2024,2024_12,Доверительный,На рефинансирование займа,Онлайн СБОЛ,QR,3 708 542,1 911 620,Тараз,"Тараз, СПФ №1 ""Алатау""",Улица,u15565,Д?урен Ибраимов,"88 088,9",0.0,"511 921,2","512 088,8",0,0,1,0,"0,1472","682,24",None,60,47,Мужской,Холост/Не замужем,0,АО Таразэнергоцентр,г.Тараз,Жамбылская область,Ойшиликский сельский округ,РЕСПУБЛИКА УЗБЕКИСТАН ...,Хорошая,Отсутствует
30291,Д\286\012241809,2024-12-23,23.12.2024 14:44,23.12.2024,2024_12,Доверительный,На потребительские цели,Онлайн СБОЛ,B-Bank,1 000 000,1 000 000,Туркестан,"Туркестан, Операционный отдел",Улица,servws,servws servws,-,0.0,"902 185,7","902 197,0",1,0,0,0,"0,07783019","737,7358491",None,48,35,Мужской,Женат/Замужем,4,,г. Туркестан,Туркестанская область,Ойшиликский сельский округ,РЕСПУБЛИКА КАЗАХСТАН ...,Хорошая,Отсутствует

In [188]:
valid_app_data.shape

(6379, 39)

In [189]:
valid_app_data = valid_app_data.iloc[:,:22]

In [185]:
valid_app_data.isnull().sum()

APPLICATIONID           0
CREATE_DATE             0
CREATE_DATETIME         0
DATA_ISSUE              0
VINTAGE                 0
PRODUCT_GROUP           0
PURPOSE_LOAN            0
OPV_REASON              0
KANAL_PRODAZH           0
 TOTALAMOUNT            0
 SUM_CREDIT_KZT         0
BRANCH                  0
SPF                     0
APPLICATION_ISA0AUTO    0
MNG_NAME_LOGIN_INIT     7
MNG_NAME_INIT           7
 DM5DPD1GCVPSUM         0
DM5DPD1SALARYSUM        0
 DM5EXPSUM              0
 DM5INCSUM              0
DM5INC                  0
DM5EXP                  0
dtype: int64

In [190]:
valid_app_data.isnull().sum()

APPLICATIONID           0
CREATE_DATE             0
CREATE_DATETIME         0
DATA_ISSUE              0
VINTAGE                 0
PRODUCT_GROUP           0
PURPOSE_LOAN            0
OPV_REASON              0
KANAL_PRODAZH           0
 TOTALAMOUNT            0
 SUM_CREDIT_KZT         0
BRANCH                  0
SPF                     0
APPLICATION_ISA0AUTO    0
MNG_NAME_LOGIN_INIT     0
MNG_NAME_INIT           0
 DM5DPD1GCVPSUM         0
DM5DPD1SALARYSUM        0
 DM5EXPSUM              0
 DM5INCSUM              0
DM5INC                  0
DM5EXP                  0
dtype: int64

In [120]:
train_app_data.columns = train_app_data.columns.str.strip()

In [121]:
train_app_data.fillna('unknown', inplace=True)

In [122]:
train_app_data['DM5DPD1GCVPSUM'] = pd.to_numeric(train_app_data['DM5DPD1GCVPSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)

train_app_data['DM5EXPSUM'] = pd.to_numeric(train_app_data['DM5EXPSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)

train_app_data['DM5INCSUM'] = pd.to_numeric(train_app_data['DM5INCSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)

In [123]:
# def clean_and_cast_values(df):
#     df = df.copy()

#     # 1. Убираем пробелы из названий колонок
#     df.columns = df.columns.str.strip()
    
#     # 2. Преобразуем числовые колонки (object → float)
#     numeric_object_cols = [
#         'TOTALAMOUNT', 'SUM_CREDIT_KZT',
#         'DM5DPD1GCVPSUM', 'DM5EXPSUM', 'DM5INCSUM',
#         'DM6SCOREN6PD', 'DM6SCOREN6', 'FINALKDN'
#     ]
#     for col in numeric_object_cols:
#         df[col] = pd.to_numeric(df[col].str.replace(' ','').str.replace(',','.').str.replace('-',''))
    
#     # 3. Специальная обработка для важного поля FINALKDN
#     if 'FINALKDN' in df.columns:
#         df['FINALKDN_is_missing'] = df['FINALKDN'].isna().astype(int)
#         df['FINALKDN'] = df['FINALKDN'].fillna(-999)

#     # 4. Категориальные переменные — заполняем 'unknown'
#     cat_cols_with_nans = [
#         'MNG_NAME_LOGIN_INIT', 'MNG_NAME_INIT',
#         'REGREGION', 'REGCOUNTY', 'REGTOWN', 'BIRTHCOUNTRY'
#     ]
#     for col in cat_cols_with_nans:
#         df[col] = df[col].fillna('unknown')

#     return df
# train_app_data = clean_and_cast_values(train_app_data)

In [124]:
def generate_numeric_time_features(df, datetime_col='CREATE_DATETIME'):
    df = df.copy()
    df[datetime_col] = pd.to_datetime(df[datetime_col])

    df['app_year'] = df[datetime_col].dt.year
    df['app_month'] = df[datetime_col].dt.month
    df['app_day'] = df[datetime_col].dt.day
    df['app_hour'] = df[datetime_col].dt.hour
    df['app_minute'] = df[datetime_col].dt.minute
    df['app_dayofweek'] = df[datetime_col].dt.dayofweek

    # Бинарные признаки строго как 0/1
    df['is_night'] = df['app_hour'].between(0, 6).astype(int)
    df['is_off_hours'] = df['app_hour'].isin([0, 1, 2, 3, 4, 5, 23]).astype(int)
    df['is_start_of_month'] = (df['app_day'] <= 3).astype(int)
    df['is_end_of_month'] = df[datetime_col].dt.is_month_end.astype(int)
    df['is_weekend'] = (df['app_dayofweek'] >= 5).astype(int)

    df['app_seconds_since_midnight'] = (
        df['app_hour'] * 3600 +
        df['app_minute'] * 60 +
        df[datetime_col].dt.second
    )

    return df

In [125]:
train_app_data = generate_numeric_time_features(train_app_data)

In [126]:
train_app_data.dtypes

APPLICATIONID                         object
CREATE_DATE                   datetime64[ns]
CREATE_DATETIME               datetime64[ns]
DATA_ISSUE                            object
VINTAGE                               object
PRODUCT_GROUP                         object
PURPOSE_LOAN                          object
OPV_REASON                            object
KANAL_PRODAZH                         object
TOTALAMOUNT                           object
SUM_CREDIT_KZT                        object
BRANCH                                object
SPF                                   object
APPLICATION_ISA0AUTO                  object
MNG_NAME_LOGIN_INIT                   object
MNG_NAME_INIT                         object
DM5DPD1GCVPSUM                       float64
DM5DPD1SALARYSUM                     float64
DM5EXPSUM                            float64
DM5INCSUM                            float64
DM5INC                                 int64
DM5EXP                                 int64
app_year                               int64
app_month                              int64
app_day                                int64
app_hour                               int64
app_minute                             int64
app_dayofweek                          int64
is_night                               int32
is_off_hours                           int32
is_start_of_month                      int32
is_end_of_month                        int32
is_weekend                             int32
app_seconds_since_midnight             int64
dtype: object

In [128]:
train_app_data['MNG_NAME_LOGIN_INIT'] = \
np.where(train_app_data['MNG_NAME_LOGIN_INIT'].str.lower().str.contains('u')\
        , 'manager'\
        , 'servws')

In [129]:
train_app_data.drop(columns = ['PRODUCT_GROUP','SPF','MNG_NAME_INIT'],axis=1, inplace=True)

In [130]:
train_app_data.head(3)

,APPLICATIONID,CREATE_DATE,CREATE_DATETIME,DATA_ISSUE,VINTAGE,PURPOSE_LOAN,OPV_REASON,KANAL_PRODAZH,TOTALAMOUNT,SUM_CREDIT_KZT,BRANCH,APPLICATION_ISA0AUTO,MNG_NAME_LOGIN_INIT,DM5DPD1GCVPSUM,DM5DPD1SALARYSUM,DM5EXPSUM,DM5INCSUM,DM5INC,DM5EXP,app_year,app_month,app_day,app_hour,app_minute,app_dayofweek,is_night,is_off_hours,is_start_of_month,is_end_of_month,is_weekend,app_seconds_since_midnight
0,Д\286\011639474,2024-10-17,2024-10-17 12:16:00,17.10.2024,2024_10,На потребительские цели,Онлайн СБОЛ,B-Bank,150 000,150 000,Алматы,Улица,servws,457066.8,0.0,2874498.7,2861073.5,0,0,2024,10,17,12,16,3,0,0,0,0,0,44160
1,Д\286\011668478,2024-10-21,2024-10-21 08:31:00,21.10.2024,2024_10,На потребительские цели,Онлайн СБОЛ,B-Bank,300 000,300 000,Караганда,Улица,servws,68850.0,0.0,558734.6,564659.8,0,0,2024,10,21,8,31,0,0,0,0,0,0,30660
2,Д\286\011681466,2024-10-22,2024-10-22 10:05:00,22.10.2024,2024_10,На потребительские цели,Онлайн СБОЛ,B-Bank,600 000,368 858,Алматы,Улица,servws,-999.0,0.0,1044469.5,1023278.0,0,1,2024,10,22,10,5,1,0,0,0,0,0,36300

In [135]:
train_app_data['TOTALAMOUNT'] = pd.to_numeric(train_app_data['TOTALAMOUNT'].str.replace(' ','').str.replace(',','.').str.replace('-',''))
train_app_data['SUM_CREDIT_KZT'] = pd.to_numeric(train_app_data['SUM_CREDIT_KZT'].str.replace(' ','').str.replace(',','.').str.replace('-',''))

In [143]:
def encode_categorical_with_dummies(df, categorical_cols, drop_first=True):
    """
    Преобразует указанные категориальные признаки в dummy-переменные (0/1).
    
    Аргументы:
    - df: исходный DataFrame
    - categorical_cols: список колонок, которые нужно закодировать
    - drop_first: если True — удаляет первый столбец, чтобы избежать мультиколлинеарности

    Возвращает:
    - df с dummy-переменными
    """
    df = df.copy()
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=False)
    return df

In [144]:
train_app_data.head(2)

,APPLICATIONID,CREATE_DATE,CREATE_DATETIME,DATA_ISSUE,VINTAGE,PURPOSE_LOAN,OPV_REASON,KANAL_PRODAZH,TOTALAMOUNT,SUM_CREDIT_KZT,BRANCH,APPLICATION_ISA0AUTO,MNG_NAME_LOGIN_INIT,DM5DPD1GCVPSUM,DM5DPD1SALARYSUM,DM5EXPSUM,DM5INCSUM,DM5INC,DM5EXP,app_year,app_month,app_day,app_hour,app_minute,app_dayofweek,is_night,is_off_hours,is_start_of_month,is_end_of_month,is_weekend,app_seconds_since_midnight
0,Д\286\011639474,2024-10-17,2024-10-17 12:16:00,17.10.2024,2024_10,На потребительские цели,Онлайн СБОЛ,B-Bank,150000,150000,Алматы,Улица,servws,457066.8,0.0,2874498.7,2861073.5,0,0,2024,10,17,12,16,3,0,0,0,0,0,44160
1,Д\286\011668478,2024-10-21,2024-10-21 08:31:00,21.10.2024,2024_10,На потребительские цели,Онлайн СБОЛ,B-Bank,300000,300000,Караганда,Улица,servws,68850.0,0.0,558734.6,564659.8,0,0,2024,10,21,8,31,0,0,0,0,0,0,30660

In [145]:
# train_app_data.rename(columns={''})

In [146]:
train_app_data.dtypes

APPLICATIONID                         object
CREATE_DATE                   datetime64[ns]
CREATE_DATETIME               datetime64[ns]
DATA_ISSUE                            object
VINTAGE                               object
PURPOSE_LOAN                          object
OPV_REASON                            object
KANAL_PRODAZH                         object
TOTALAMOUNT                            int64
SUM_CREDIT_KZT                         int64
BRANCH                                object
APPLICATION_ISA0AUTO                  object
MNG_NAME_LOGIN_INIT                   object
DM5DPD1GCVPSUM                       float64
DM5DPD1SALARYSUM                     float64
DM5EXPSUM                            float64
DM5INCSUM                            float64
DM5INC                                 int64
DM5EXP                                 int64
app_year                               int64
app_month                              int64
app_day                                int64
app_hour                               int64
app_minute                             int64
app_dayofweek                          int64
is_night                               int32
is_off_hours                           int32
is_start_of_month                      int32
is_end_of_month                        int32
is_weekend                             int32
app_seconds_since_midnight             int64
dtype: object

In [147]:
categorical_cols = ['PURPOSE_LOAN', 'OPV_REASON', 'KANAL_PRODAZH','BRANCH','APPLICATION_ISA0AUTO','MNG_NAME_LOGIN_INIT']
train_app_data_encoded = encode_categorical_with_dummies(train_app_data, categorical_cols)

In [148]:
train_app_data['KANAL_PRODAZH'].value_counts()

B-Bank    12400
QR         4804
WEB        1182
Name: KANAL_PRODAZH, dtype: int64

In [149]:
train_app_data_encoded

,APPLICATIONID,CREATE_DATE,CREATE_DATETIME,DATA_ISSUE,VINTAGE,TOTALAMOUNT,SUM_CREDIT_KZT,DM5DPD1GCVPSUM,DM5DPD1SALARYSUM,DM5EXPSUM,DM5INCSUM,DM5INC,DM5EXP,app_year,app_month,app_day,app_hour,app_minute,app_dayofweek,is_night,is_off_hours,is_start_of_month,is_end_of_month,is_weekend,app_seconds_since_midnight,PURPOSE_LOAN_На потребительские цели,PURPOSE_LOAN_На рефинансирование займа,PURPOSE_LOAN_На рефинансирование займа и потребительские цели,OPV_REASON_NEW САЙТ,OPV_REASON_Онлайн СБОЛ,KANAL_PRODAZH_B-Bank,KANAL_PRODAZH_QR,KANAL_PRODAZH_WEB,BRANCH_Актау,BRANCH_Актобе,BRANCH_Алматинская область,BRANCH_Алматы,BRANCH_Астана,BRANCH_Атырау,BRANCH_Караганда,BRANCH_Кокшетау,BRANCH_Костанай,BRANCH_Кызылорда,BRANCH_Павлодар,BRANCH_Петропавловск,BRANCH_Семей,BRANCH_Тараз,BRANCH_Туркестан,BRANCH_Уральск,BRANCH_Усть-Каменогорск,BRANCH_Шымкент,APPLICATION_ISA0AUTO_Зарплатники,APPLICATION_ISA0AUTO_Улица,MNG_NAME_LOGIN_INIT_manager,MNG_NAME_LOGIN_INIT_servws
0,Д\286\011639474,2024-10-17,2024-10-17 12:16:00,17.10.2024,2024_10,150000,150000,457066.8,0.0,2874498.7,2861073.5,0,0,2024,10,17,12,16,3,0,0,0,0,0,44160,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
1,Д\286\011668478,2024-10-21,2024-10-21 08:31:00,21.10.2024,2024_10,300000,300000,68850.0,0.0,558734.6,564659.8,0,0,2024,10,21,8,31,0,0,0,0,0,0,30660,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
2,Д\286\011681466,2024-10-22,2024-10-22 10:05:00,22.10.2024,2024_10,600000,368858,-999.0,0.0,1044469.5,1023278.0,0,1,2024,10,22,10,5,1,0,0,0,0,0,36300,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
3,Д\286\011721797,2024-10-26,2024-10-26 14:13:00,26.10.2024,2024_10,200000,217391,-999.0,0.0,1048790.4,1046686.8,0,1,2024,10,26,14,13,5,0,0,0,0,1,51180,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
4,Д\286\012045593,2024-01-12,2024-01-12 19:14:00,02.12.2024,2024_12,150000,150000,-999.0,0.0,982182.2,942380.7,0,1,2024,1,12,19,14,4,0,0,0,0,0,69240,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30282,Д\286\011681076,2024-10-22,2024-10-22 09:29:00,22.10.2024,2024_10,500000,520833,-999.0,0.0,1006182.6,1008260.8,1,0,2024,10,22,9,29,1,0,0,0,0,0,34140,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
30283,Д\286\011772653,2024-01-11,2024-01-11 10:53:00,01.11.2024,2024_11,5844910,3108995,204525.0,0.0,1333113.3,1346874.0,0,0,2024,1,11,10,53,3,0,0,0,0,0,39180,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
30285,Д\286\011635188,2024-10-16,2024-10-16 19:34:00,16.10.2024,2024_10,1000000,991992,176761.8,0.0,3291000.3,3278894.5,0,0,2024,10,16,19,34,2,0,0,0,0,0,70440,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1
30286,Д\286\011720017,2024-10-26,2024-10-26 11:28:00,26.10.2024,2024_10,1500000,1000000,-999.0,0.0,1191303.8,1192192.5,1,0,2024,10,26,11,28,5,0,0,0,0,1,41280,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1
30288,Д\286\011806166,2024-05-11,2024-05-11 12:19:00,05.11.2024,2024_11,300000,326086,-999.0,0.0,1635937.0,1636439.2,1,0,2024,5,11,12,19,5,0,0,0,0,1,44340,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1

In [153]:
train_app_data_encoded.dtypes

APPLICATIONID                                                            object
CREATE_DATE                                                      datetime64[ns]
CREATE_DATETIME                                                  datetime64[ns]
DATA_ISSUE                                                               object
VINTAGE                                                                  object
TOTALAMOUNT                                                               int64
SUM_CREDIT_KZT                                                            int64
DM5DPD1GCVPSUM                                                          float64
DM5DPD1SALARYSUM                                                        float64
DM5EXPSUM                                                               float64
DM5INCSUM                                                               float64
DM5INC                                                                    int64
DM5EXP                                                                    int64
app_year                                                                  int64
app_month                                                                 int64
app_day                                                                   int64
app_hour                                                                  int64
app_minute                                                                int64
app_dayofweek                                                             int64
is_night                                                                  int32
is_off_hours                                                              int32
is_start_of_month                                                         int32
is_end_of_month                                                           int32
is_weekend                                                                int32
app_seconds_since_midnight                                                int64
PURPOSE_LOAN_На потребительские цели                                      uint8
PURPOSE_LOAN_На рефинансирование займа                                    uint8
PURPOSE_LOAN_На рефинансирование займа и потребительские цели             uint8
OPV_REASON_NEW САЙТ                                                       uint8
OPV_REASON_Онлайн СБОЛ                                                    uint8
KANAL_PRODAZH_B-Bank                                                      uint8
KANAL_PRODAZH_QR                                                          uint8
KANAL_PRODAZH_WEB                                                         uint8
BRANCH_Актау                                                              uint8
BRANCH_Актобе                                                             uint8
BRANCH_Алматинская область                                                uint8
BRANCH_Алматы                                                             uint8
BRANCH_Астана                                                             uint8
BRANCH_Атырау                                                             uint8
BRANCH_Караганда                                                          uint8
BRANCH_Кокшетау                                                           uint8
BRANCH_Костанай                                                           uint8
BRANCH_Кызылорда                                                          uint8
BRANCH_Павлодар                                                           uint8
BRANCH_Петропавловск                                                      uint8
BRANCH_Семей                                                              uint8
BRANCH_Тараз                                                              uint8
BRANCH_Туркестан                                                          uint8
BRANCH_Уральск                                                            uint8
BRANCH_Усть-Каменогорск                                                   uint8
BRANCH_Шымкент                                                            uint8
APPLICATION_ISA0AUTO_Зарплатники                                          uint8
APPLICATION_ISA0AUTO_Улица                                                uint8
MNG_NAME_LOGIN_INIT_manager                                               uint8
MNG_NAME_LOGIN_INIT_servws                                                uint8
dtype: object

In [154]:
train_app_data_encoded.to_csv('train_app_data_serg.csv')

In [165]:
pd.to_datetime(train_app_data_encoded['DATA_ISSUE'], dayfirst=True)

0       2024-10-17
1       2024-10-21
2       2024-10-22
3       2024-10-26
4       2024-12-02
           ...
30282   2024-10-22
30283   2024-11-01
30285   2024-10-16
30286   2024-10-26
30288   2024-11-05
Name: DATA_ISSUE, Length: 18386, dtype: datetime64[ns]

In [171]:
pd.to_datetime(train_app_data_encoded['CREATE_DATE']).dt.date

0        2024-10-17
1        2024-10-21
2        2024-10-22
3        2024-10-26
4        2024-01-12
            ...
30282    2024-10-22
30283    2024-01-11
30285    2024-10-16
30286    2024-10-26
30288    2024-05-11
Name: CREATE_DATE, Length: 18386, dtype: object

In [173]:
train_app_data_encoded[pd.to_datetime(train_app_data_encoded['CREATE_DATE']).dt.date != \
                      pd.to_datetime(train_app_data_encoded['DATA_ISSUE'], dayfirst=True).dt.date]

,APPLICATIONID,CREATE_DATE,CREATE_DATETIME,DATA_ISSUE,VINTAGE,TOTALAMOUNT,SUM_CREDIT_KZT,DM5DPD1GCVPSUM,DM5DPD1SALARYSUM,DM5EXPSUM,DM5INCSUM,DM5INC,DM5EXP,app_year,app_month,app_day,app_hour,app_minute,app_dayofweek,is_night,is_off_hours,is_start_of_month,is_end_of_month,is_weekend,app_seconds_since_midnight,PURPOSE_LOAN_На потребительские цели,PURPOSE_LOAN_На рефинансирование займа,PURPOSE_LOAN_На рефинансирование займа и потребительские цели,OPV_REASON_NEW САЙТ,OPV_REASON_Онлайн СБОЛ,KANAL_PRODAZH_B-Bank,KANAL_PRODAZH_QR,KANAL_PRODAZH_WEB,BRANCH_Актау,BRANCH_Актобе,BRANCH_Алматинская область,BRANCH_Алматы,BRANCH_Астана,BRANCH_Атырау,BRANCH_Караганда,BRANCH_Кокшетау,BRANCH_Костанай,BRANCH_Кызылорда,BRANCH_Павлодар,BRANCH_Петропавловск,BRANCH_Семей,BRANCH_Тараз,BRANCH_Туркестан,BRANCH_Уральск,BRANCH_Усть-Каменогорск,BRANCH_Шымкент,APPLICATION_ISA0AUTO_Зарплатники,APPLICATION_ISA0AUTO_Улица,MNG_NAME_LOGIN_INIT_manager,MNG_NAME_LOGIN_INIT_servws
4,Д\286\012045593,2024-01-12,2024-01-12 19:14:00,02.12.2024,2024_12,150000,150000,-999.0,0.0,982182.2,942380.7,0,1,2024,1,12,19,14,4,0,0,0,0,0,69240,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
5,Д\286\012080774,2024-05-12,2024-05-12 14:02:00,05.12.2024,2024_12,400000,400000,1039122.0,0.0,3046949.0,3065456.7,0,0,2024,5,12,14,2,6,0,0,0,0,1,50520,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
6,Д\286\012047665,2024-02-12,2024-02-12 10:36:00,06.12.2024,2024_12,200000,212765,60750.0,0.0,860799.3,859679.8,0,0,2024,2,12,10,36,0,0,0,0,0,0,38160,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
7,Д\286\012112597,2024-09-12,2024-09-12 16:14:00,10.12.2024,2024_12,1200000,1000000,-999.0,0.0,1109622.9,1107453.3,0,1,2024,9,12,16,14,3,0,0,0,0,0,58440,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
12,Д\286\011480586,2024-01-10,2024-01-10 09:34:00,01.10.2024,2024_10,380000,404255,62177.0,0.0,657769.5,656592.6,0,1,2024,1,10,9,34,2,0,0,0,0,0,34440,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30275,Д\286\011506609,2024-03-10,2024-03-10 12:08:00,03.10.2024,2024_10,150000,150000,-999.0,0.0,744232.0,743985.8,0,1,2024,3,10,12,8,6,0,0,0,0,1,43680,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
30276,Д\286\011773583,2024-01-11,2024-01-11 11:46:00,01.11.2024,2024_11,1000000,1086956,301962.6,0.0,853304.1,837617.0,0,0,2024,1,11,11,46,3,0,0,0,0,0,42360,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
30278,Д\286\011563198,2024-09-10,2024-09-10 12:08:00,09.10.2024,2024_10,700000,744680,159655.2,0.0,539615.7,543078.5,0,0,2024,9,10,12,8,1,0,0,0,0,0,43680,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
30283,Д\286\011772653,2024-01-11,2024-01-11 10:53:00,01.11.2024,2024_11,5844910,3108995,204525.0,0.0,1333113.3,1346874.0,0,0,2024,1,11,10,53,3,0,0,0,0,0,39180,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
30288,Д\286\011806166,2024-05-11,2024-05-11 12:19:00,05.11.2024,2024_11,300000,326086,-999.0,0.0,1635937.0,1636439.2,1,0,2024,5,11,12,19,5,0,0,0,0,1,44340,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1

In [ ]:
# train -----------------------------------------------------------------------

In [5]:
train_app_data = pd.read_parquet(r'C:\Users\makog\ai_hac\hackathon\data\train_app_data.parquet')

train_app_data.tail()

train_app_data = train_app_data.iloc[:,:22]

train_app_data.isnull().sum()

train_app_data.columns = train_app_data.columns.str.strip()

train_app_data.fillna('unknown', inplace=True)

train_app_data['DM5DPD1GCVPSUM'] = pd.to_numeric(train_app_data['DM5DPD1GCVPSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)

train_app_data['DM5EXPSUM'] = pd.to_numeric(train_app_data['DM5EXPSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)

train_app_data['DM5INCSUM'] = pd.to_numeric(train_app_data['DM5INCSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)

# def clean_and_cast_values(df):
#     df = df.copy()

#     # 1. Убираем пробелы из названий колонок
#     df.columns = df.columns.str.strip()
    
#     # 2. Преобразуем числовые колонки (object → float)
#     numeric_object_cols = [
#         'TOTALAMOUNT', 'SUM_CREDIT_KZT',
#         'DM5DPD1GCVPSUM', 'DM5EXPSUM', 'DM5INCSUM',
#         'DM6SCOREN6PD', 'DM6SCOREN6', 'FINALKDN'
#     ]
#     for col in numeric_object_cols:
#         df[col] = pd.to_numeric(df[col].str.replace(' ','').str.replace(',','.').str.replace('-',''))
    
#     # 3. Специальная обработка для важного поля FINALKDN
#     if 'FINALKDN' in df.columns:
#         df['FINALKDN_is_missing'] = df['FINALKDN'].isna().astype(int)
#         df['FINALKDN'] = df['FINALKDN'].fillna(-999)

#     # 4. Категориальные переменные — заполняем 'unknown'
#     cat_cols_with_nans = [
#         'MNG_NAME_LOGIN_INIT', 'MNG_NAME_INIT',
#         'REGREGION', 'REGCOUNTY', 'REGTOWN', 'BIRTHCOUNTRY'
#     ]
#     for col in cat_cols_with_nans:
#         df[col] = df[col].fillna('unknown')

#     return df
# train_app_data = clean_and_cast_values(train_app_data)



def generate_numeric_time_features(df, datetime_col='CREATE_DATETIME'):
    df = df.copy()
    df[datetime_col] = pd.to_datetime(df[datetime_col])

    df['app_year'] = df[datetime_col].dt.year
    df['app_month'] = df[datetime_col].dt.month
    df['app_day'] = df[datetime_col].dt.day
    df['app_hour'] = df[datetime_col].dt.hour
    df['app_minute'] = df[datetime_col].dt.minute
    df['app_dayofweek'] = df[datetime_col].dt.dayofweek

    # Бинарные признаки строго как 0/1
    df['is_night'] = df['app_hour'].between(0, 6).astype(int)
    df['is_off_hours'] = df['app_hour'].isin([0, 1, 2, 3, 4, 5, 23]).astype(int)
    df['is_start_of_month'] = (df['app_day'] <= 3).astype(int)
    df['is_end_of_month'] = df[datetime_col].dt.is_month_end.astype(int)
    df['is_weekend'] = (df['app_dayofweek'] >= 5).astype(int)

    df['app_seconds_since_midnight'] = (
        df['app_hour'] * 3600 +
        df['app_minute'] * 60 +
        df[datetime_col].dt.second
    )

    return df

train_app_data = generate_numeric_time_features(train_app_data)

train_app_data.dtypes

train_app_data['MNG_NAME_LOGIN_INIT'] = \
np.where(train_app_data['MNG_NAME_LOGIN_INIT'].str.lower().str.contains('u')\
        , 'manager'\
        , 'servws')

train_app_data.drop(columns = ['PRODUCT_GROUP','SPF','MNG_NAME_INIT'],axis=1, inplace=True)

train_app_data.head(3)

train_app_data['TOTALAMOUNT'] = pd.to_numeric(train_app_data['TOTALAMOUNT'].str.replace(' ','').str.replace(',','.').str.replace('-',''))
train_app_data['SUM_CREDIT_KZT'] = pd.to_numeric(train_app_data['SUM_CREDIT_KZT'].str.replace(' ','').str.replace(',','.').str.replace('-',''))

def encode_categorical_with_dummies(df, categorical_cols, drop_first=True):
    """
    Преобразует указанные категориальные признаки в dummy-переменные (0/1).
    
    Аргументы:
    - df: исходный DataFrame
    - categorical_cols: список колонок, которые нужно закодировать
    - drop_first: если True — удаляет первый столбец, чтобы избежать мультиколлинеарности

    Возвращает:
    - df с dummy-переменными
    """
    df = df.copy()
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=False)
    return df


train_app_data.head(2)

# train_app_data.rename(columns={''})

train_app_data.dtypes

categorical_cols = ['PURPOSE_LOAN', 'OPV_REASON', 'KANAL_PRODAZH','BRANCH','APPLICATION_ISA0AUTO','MNG_NAME_LOGIN_INIT']
train_app_data_encoded = encode_categorical_with_dummies(train_app_data, categorical_cols)

train_app_data['KANAL_PRODAZH'].value_counts()

train_app_data_encoded

train_app_data_encoded.dtypes

In [ ]:
# valid -----------------------------------------------------------------------

In [2]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML

# Показывать все колонки
pd.set_option('display.max_columns', None)

# Настроить стиль для горизонтальной прокрутки
def show_scrollable(df):
    display(HTML(df.to_html(notebook=True, max_rows=20, max_cols=None, escape=False)))
    
    # Альтернативно, если нужен скролл:
    display(HTML(f"""
        <div style="overflow-x: auto; max-width:100%;">
            {df.to_html()}
        </div>
    """))


valid_app_data = pd.read_parquet(r'C:\Users\makog\ai_hac\hackathon\data\valid_app_data.parquet')

# valid_app_data.tail()

valid_app_data = valid_app_data.iloc[:,:22]

# valid_app_data.isnull().sum()

valid_app_data.columns = valid_app_data.columns.str.strip()

valid_app_data.fillna('unknown', inplace=True)

valid_app_data['DM5DPD1GCVPSUM'] = pd.to_numeric(valid_app_data['DM5DPD1GCVPSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)

valid_app_data['DM5EXPSUM'] = pd.to_numeric(valid_app_data['DM5EXPSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)

valid_app_data['DM5INCSUM'] = pd.to_numeric(valid_app_data['DM5INCSUM'].str.replace(' ','').str.replace(',','.').str.replace('-','')).fillna(-999)


def generate_numeric_time_features(df, datetime_col='CREATE_DATETIME'):
    df = df.copy()
    df[datetime_col] = pd.to_datetime(df[datetime_col])

    df['app_year'] = df[datetime_col].dt.year
    df['app_month'] = df[datetime_col].dt.month
    df['app_day'] = df[datetime_col].dt.day
    df['app_hour'] = df[datetime_col].dt.hour
    df['app_minute'] = df[datetime_col].dt.minute
    df['app_dayofweek'] = df[datetime_col].dt.dayofweek

    # Бинарные признаки строго как 0/1
    df['is_night'] = df['app_hour'].between(0, 6).astype(int)
    df['is_off_hours'] = df['app_hour'].isin([0, 1, 2, 3, 4, 5, 23]).astype(int)
    df['is_start_of_month'] = (df['app_day'] <= 3).astype(int)
    df['is_end_of_month'] = df[datetime_col].dt.is_month_end.astype(int)
    df['is_weekend'] = (df['app_dayofweek'] >= 5).astype(int)

    df['app_seconds_since_midnight'] = (
        df['app_hour'] * 3600 +
        df['app_minute'] * 60 +
        df[datetime_col].dt.second
    )

    return df

valid_app_data = generate_numeric_time_features(valid_app_data)

# valid_app_data.dtypes

valid_app_data['MNG_NAME_LOGIN_INIT'] = \
np.where(valid_app_data['MNG_NAME_LOGIN_INIT'].str.lower().str.contains('u')\
        , 'manager'\
        , 'servws')

valid_app_data.drop(columns = ['PRODUCT_GROUP','SPF','MNG_NAME_INIT'],axis=1, inplace=True)

# valid_app_data.head(3)

valid_app_data['TOTALAMOUNT'] = pd.to_numeric(valid_app_data['TOTALAMOUNT'].str.replace(' ','').str.replace(',','.').str.replace('-',''))
valid_app_data['SUM_CREDIT_KZT'] = pd.to_numeric(valid_app_data['SUM_CREDIT_KZT'].str.replace(' ','').str.replace(',','.').str.replace('-',''))

def encode_categorical_with_dummies(df, categorical_cols, drop_first=True):
    """
    Преобразует указанные категориальные признаки в dummy-переменные (0/1).
    
    Аргументы:
    - df: исходный DataFrame
    - categorical_cols: список колонок, которые нужно закодировать
    - drop_first: если True — удаляет первый столбец, чтобы избежать мультиколлинеарности

    Возвращает:
    - df с dummy-переменными
    """
    df = df.copy()
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=False)
    return df


# valid_app_data.head(2)

# valid_app_data.rename(columns={''})

# valid_app_data.dtypes

categorical_cols = ['PURPOSE_LOAN', 'OPV_REASON', 'KANAL_PRODAZH','BRANCH','APPLICATION_ISA0AUTO','MNG_NAME_LOGIN_INIT']
valid_app_data_encoded = encode_categorical_with_dummies(valid_app_data, categorical_cols)

# valid_app_data['KANAL_PRODAZH'].value_counts()

# valid_app_data_encoded

# valid_app_data_encoded.dtypes

In [3]:
valid_app_data_encoded

,APPLICATIONID,CREATE_DATE,CREATE_DATETIME,DATA_ISSUE,VINTAGE,TOTALAMOUNT,SUM_CREDIT_KZT,DM5DPD1GCVPSUM,DM5DPD1SALARYSUM,DM5EXPSUM,DM5INCSUM,DM5INC,DM5EXP,app_year,app_month,app_day,app_hour,app_minute,app_dayofweek,is_night,is_off_hours,is_start_of_month,is_end_of_month,is_weekend,app_seconds_since_midnight,PURPOSE_LOAN_На потребительские цели,PURPOSE_LOAN_На рефинансирование займа,PURPOSE_LOAN_На рефинансирование займа и потребительские цели,OPV_REASON_NEW САЙТ,OPV_REASON_Онлайн СБОЛ,KANAL_PRODAZH_B-Bank,KANAL_PRODAZH_QR,KANAL_PRODAZH_WEB,BRANCH_Актау,BRANCH_Актобе,BRANCH_Алматинская область,BRANCH_Алматы,BRANCH_Астана,BRANCH_Атырау,BRANCH_Караганда,BRANCH_Кокшетау,BRANCH_Костанай,BRANCH_Кызылорда,BRANCH_Павлодар,BRANCH_Петропавловск,BRANCH_Семей,BRANCH_Тараз,BRANCH_Туркестан,BRANCH_Уральск,BRANCH_Усть-Каменогорск,BRANCH_Шымкент,APPLICATION_ISA0AUTO_Зарплатники,APPLICATION_ISA0AUTO_Улица,MNG_NAME_LOGIN_INIT_manager,MNG_NAME_LOGIN_INIT_servws
8,Д\286\012220838,2024-12-20,2024-12-20 16:28:00,20.12.2024,2024_12,1800000,1800000,114750.0,0.0,4945035.7,4943066.0,0,0,2024,12,20,16,28,4,0,0,0,0,0,59280,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
9,Д\286\012249879,2024-12-24,2024-12-24 11:51:00,24.12.2024,2024_12,560000,608695,86884.7,0.0,1903547.2,1905279.6,1,0,2024,12,24,11,51,1,0,0,0,0,0,42660,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
10,Д\286\012273876,2024-12-26,2024-12-26 16:56:00,26.12.2024,2024_12,1500000,1000000,-999.0,0.0,5806962.0,5805763.7,0,1,2024,12,26,16,56,3,0,0,0,0,0,60960,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
11,Д\286\012288632,2024-12-28,2024-12-28 16:13:00,30.12.2024,2024_12,200000,200000,68850.0,0.0,915976.7,915784.5,0,1,2024,12,28,16,13,5,0,0,0,0,1,58380,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
29,Д\286\011592446,2024-12-10,2024-12-10 11:52:00,12.10.2024,2024_10,200000,212765,233769.8,0.0,446342.8,447020.4,0,0,2024,12,10,11,52,1,0,0,0,0,0,42720,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30261,Д\286\012275441,2024-12-26,2024-12-26 20:52:00,27.12.2024,2024_12,150000,150000,311175.0,0.0,1484270.7,1481724.7,0,0,2024,12,26,20,52,3,0,0,0,0,0,75120,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1
30272,Д\286\012141252,2024-12-12,2024-12-12 12:19:00,12.12.2024,2024_12,1500000,1000000,-999.0,0.0,553521.7,553468.8,0,1,2024,12,12,12,19,3,0,0,0,0,0,44340,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0
30273,Д\286\012161697,2024-12-14,2024-12-14 11:52:00,14.12.2024,2024_12,150000,150000,-999.0,0.0,410992.0,411387.7,1,0,2024,12,14,11,52,5,0,0,0,0,1,42720,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1
30274,Д\286\012248249,2024-12-24,2024-12-24 10:04:00,24.12.2024,2024_12,3708542,1911620,88088.9,0.0,511921.2,512088.8,0,0,2024,12,24,10,4,1,0,0,0,0,0,36240,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0
30291,Д\286\012241809,2024-12-23,2024-12-23 14:44:00,23.12.2024,2024_12,1000000,1000000,-999.0,0.0,902185.7,902197.0,1,0,2024,12,23,14,44,0,0,0,0,0,0,53040,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1

In [5]:
valid_app_data_encoded['APPLICATIONID'].nunique()

6379

In [4]:
valid_app_data_encoded.dtypes

APPLICATIONID                                                            object
CREATE_DATE                                                      datetime64[ns]
CREATE_DATETIME                                                  datetime64[ns]
DATA_ISSUE                                                               object
VINTAGE                                                                  object
TOTALAMOUNT                                                               int64
SUM_CREDIT_KZT                                                            int64
DM5DPD1GCVPSUM                                                          float64
DM5DPD1SALARYSUM                                                        float64
DM5EXPSUM                                                               float64
DM5INCSUM                                                               float64
DM5INC                                                                    int64
DM5EXP                                                                    int64
app_year                                                                  int64
app_month                                                                 int64
app_day                                                                   int64
app_hour                                                                  int64
app_minute                                                                int64
app_dayofweek                                                             int64
is_night                                                                  int32
is_off_hours                                                              int32
is_start_of_month                                                         int32
is_end_of_month                                                           int32
is_weekend                                                                int32
app_seconds_since_midnight                                                int64
PURPOSE_LOAN_На потребительские цели                                      uint8
PURPOSE_LOAN_На рефинансирование займа                                    uint8
PURPOSE_LOAN_На рефинансирование займа и потребительские цели             uint8
OPV_REASON_NEW САЙТ                                                       uint8
OPV_REASON_Онлайн СБОЛ                                                    uint8
KANAL_PRODAZH_B-Bank                                                      uint8
KANAL_PRODAZH_QR                                                          uint8
KANAL_PRODAZH_WEB                                                         uint8
BRANCH_Актау                                                              uint8
BRANCH_Актобе                                                             uint8
BRANCH_Алматинская область                                                uint8
BRANCH_Алматы                                                             uint8
BRANCH_Астана                                                             uint8
BRANCH_Атырау                                                             uint8
BRANCH_Караганда                                                          uint8
BRANCH_Кокшетау                                                           uint8
BRANCH_Костанай                                                           uint8
BRANCH_Кызылорда                                                          uint8
BRANCH_Павлодар                                                           uint8
BRANCH_Петропавловск                                                      uint8
BRANCH_Семей                                                              uint8
BRANCH_Тараз                                                              uint8
BRANCH_Туркестан                                                          uint8
BRANCH_Уральск                                                            uint8
BRANCH_Усть-Каменогорск                                                   uint8
BRANCH_Шымкент                                                            uint8
APPLICATION_ISA0AUTO_Зарплатники                                          uint8
APPLICATION_ISA0AUTO_Улица                                                uint8
MNG_NAME_LOGIN_INIT_manager                                               uint8
MNG_NAME_LOGIN_INIT_servws                                                uint8
dtype: object

In [15]:
valid_app_data_encoded.shape

(6379, 55)

In [6]:
valid_app_data_encoded.to_csv('valid_app_data_serg.csv')